### ISSUE TITLE
Tutorial?

### ISSUE THREAD

**Issue by ccorcos** [OpenLightingProject/raspberrypi#12]
I want to control a simple RGB light with my Raspberry Pi over 3-pin DMX512. I have no idea how I should do this. I'm seeing a variety of shields that work over USB or LAN, but I just want a simple way of programmign a color. Any suggestions?

**Comment by peternewman** [comment]
Hi @ccorcos I'll give you a brief answer now, but if you've got further questions, can you ask them on the mailing list, this repo is actually for the code that generates our Raspberry Pi images, rather than for general Pi issues:
https://groups.google.com/forum/#!forum/open-lighting

You'll need to generate DMX somehow to control your light, so you've got a few options (assuming you don't already own an interface). Depending on your circumstance, how reliable it wants to be and how much money you want to spend:
- UART https://github.com/OpenLightingProject/ola/blob/master/plugins/uartdmx/README.md
- USB https://www.openlighting.org/ola/get-help/ola-faq/#What_are_the_recommended_USB_Device_to_use_with_OLA

You can probably ignore the Ethernet options unless you want to spend money unnecessarily, or need the Pi and light to be separated over a large distance and you don't want to run DMX cable for some reason.
